# Generated by Django 4.2.5 on 2024-06-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='art',
            new_name='cart',
        ),
    ]
